/**
 * Forensic Report Generator
 *
 * Generates comprehensive investigation reports in JSON and PDF format.
 */

import crypto from 'node:crypto';
import PDFDocument from 'pdfkit';
import Evidence from '../models/Evidence.js';
import { timelineService } from './timelineService.js';
import { verificationService } from './verificationService.js';
import { caseService } from './caseService.js';
import { custodyService } from './custodyService.js';
import { auditService } from './auditService.js';
import { NotFoundError } from '../utils/errors.js';
import { logger } from '../utils/logger.js';

export class ReportService {
    async generateEvidenceReport(evidenceId, format = 'json', mcpContext) {
        const evidence = await Evidence.findOne({ evidence_id: evidenceId }).lean();
        if (!evidence) throw new NotFoundError('Evidence');

        const [timeline, verification, caseData] = await Promise.all([
            timelineService.getTimeline(evidenceId),
            verificationService.verifyEvidence(evidenceId, mcpContext),
            caseService.getCaseById(evidence.case_id, mcpContext).catch(() => null),
        ]);

        await custodyService.createEvent({
            evidence_id: evidenceId,
            action: 'EXPORT_EVIDENCE',
            actor_id: mcpContext.user_id,
            actor_name: mcpContext.user_id,
            actor_role: mcpContext.role,
            details: { format, report_type: 'forensic_evidence_report' },
        }, mcpContext);

        const reportData = {
            report_metadata: {
                report_type: 'FORENSIC_EVIDENCE_REPORT',
                report_id: crypto.randomUUID(),
                generated_at: new Date().toISOString(),
                generated_by: mcpContext.user_id,
                format,
            },
            case_information: caseData ? {
                case_id: caseData.case_id,
                case_name: caseData.case_name,
                status: caseData.status,
                classification: caseData.classification,
                created_by: caseData.created_by,
                created_at: caseData.created_at,
            } : null,
            evidence_metadata: {
                evidence_id: evidence.evidence_id,
                file_name: evidence.original_name,
                mime_type: evidence.mime_type,
                file_size: evidence.file_size,
                file_size_readable: formatBytes(evidence.file_size),
                file_hash_sha256: evidence.file_hash,
                uploaded_by: evidence.uploaded_by,
                current_custodian: evidence.current_custodian,
                access_count: evidence.access_count,
                created_at: evidence.created_at,
                tags: evidence.tags,
                description: evidence.description,
            },
            verification_results: {
                overall_result: verification.overall_result,
                methods_run: verification.methods_run || [],
                verification_timestamp: verification.verified_at || new Date().toISOString(),
                tampering_found: verification.overall_result !== 'pass',
            },
            digital_signatures: evidence.digital_signatures.map((sig) => ({
                signer_id: sig.signer_id,
                signed_at: sig.signed_at,
                data_hash: sig.data_hash,
            })),
            chain_of_custody: timeline.timeline.map((event) => ({
                timestamp: event.timestamp,
                action: event.label,
                actor: event.actor.name,
                role: event.actor.role,
                ip_address: event.ip_address,
                event_hash: event.event_hash,
                details: event.details,
            })),
            forensic_analysis: verification.forensic_analysis || null,
            legal_notice: {
                statement: 'This report is generated by TraceVault Digital Evidence Integrity Platform. ' +
                    'All evidence has been stored with SHA-256 cryptographic hashing and AES-256-CBC/GCM encryption. ' +
                    'The chain of custody is strictly maintained through cryptographic tamper-evident hash chains.',
                platform: 'TraceVault v2.0.0 Enterprise',
                standards: ['ISO/IEC 27037:2012', 'NIST SP 800-86', 'RFC 3161'],
            },
        };

        if (format === 'pdf') {
            return this._generatePDF(reportData);
        }

        logger.info({ evidenceId, format }, 'Report generated');
        return reportData;
    }

    async generateCaseReport(caseId, format = 'json', mcpContext) {
        const caseData = await Case.findOne({ case_id: caseId }).lean();
        if (!caseData) throw new NotFoundError('Case');

        const [evidences, investigators] = await Promise.all([
            Evidence.find({ case_id: caseId }).lean(),
            // Assuming we might want to resolve names, but for now we follow schema
            Promise.resolve(caseData.investigators || [])
        ]);

        const reportData = {
            report_metadata: {
                report_type: 'FORENSIC_CASE_SUMMARY',
                report_id: crypto.randomUUID(),
                generated_at: new Date().toISOString(),
                generated_by: mcpContext.user_id,
                format,
            },
            case_information: {
                case_id: caseData.case_id,
                case_name: caseData.case_name,
                description: caseData.description,
                status: caseData.status,
                classification: caseData.classification,
                created_by: caseData.created_by,
                created_at: caseData.created_at,
            },
            investigators: caseData.investigators, // IDs
            notes: (caseData.notes || []).map(n => ({
                author: n.author_name,
                content: n.content,
                timestamp: n.created_at
            })),
            linked_evidence: evidences.map(e => ({
                evidence_id: e.evidence_id,
                file_name: e.original_name,
                mime_type: e.mime_type,
                file_size_readable: formatBytes(e.file_size),
                hash: e.file_hash,
                uploaded_by: e.uploaded_by,
                created_at: e.created_at,
                integrity: e.integrity_status || 'verified'
            })),
            legal_notice: {
                statement: 'This report is generated by TraceVault. All linked evidence possesses independently auditable hash chains.',
                platform: 'TraceVault v2.0.0 Enterprise',
                standards: ['ISO/IEC 27037:2012', 'NIST SP 800-86'],
            },
        };

        if (format === 'pdf') {
            return this._generateCasePDF(reportData);
        }

        logger.info({ caseId, format }, 'Case Summary generated');
        return reportData;
    }

    async generateAuditReport(format = 'json', mcpContext) {
        // Fetch last 500 significant audit logs for export to avoid massive PDF size limits
        const { logs } = await auditService.getLogs({}, 1, 500);

        const reportData = {
            report_metadata: {
                report_type: 'SYSTEM_AUDIT_TRAIL',
                report_id: crypto.randomUUID(),
                generated_at: new Date().toISOString(),
                generated_by: mcpContext.user_id,
                format,
                total_events_exported: logs.length
            },
            audit_events: logs.map(l => ({
                timestamp: l.timestamp,
                log_id: l.log_id,
                user: l.actor_name || l.user_id || 'System',
                action: l.action,
                endpoint: l.endpoint,
                ip_address: l.ip_address,
                mac_address: l.mac_address || 'unavailable',
                device_fingerprint: l.device_fingerprint,
                status: l.status_code
            })),
            legal_notice: {
                statement: 'This audit trail contains strictly immutable events securely written to append-only forensic datastores.',
                platform: 'TraceVault v2.0.0 Enterprise',
                standards: ['NIST SP 800-92'],
            },
        };

        if (format === 'pdf') {
            return this._generateAuditPDF(reportData);
        }

        logger.info({ format }, 'Audit Trail generated');
        return reportData;
    }

    _generatePDF(reportData) {
        return new Promise((resolve, reject) => {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const chunks = [];

            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            const BRAND_COLOR = '#059669'; // Emerald 600
            const SEC_COLOR = '#10b981'; // Emerald 500
            const TEXT_COLOR = '#111827'; // Slate 900
            const MUTED_TEXT = '#6b7280'; // Slate 500
            const LIGHT_BG = '#f8fafc'; // Slate 50
            const BORDER_COLOR = '#e2e8f0'; // Slate 200
            const ALERT_RED = '#b91c1c';
            const ALERT_GREEN = '#15803d';

            // Global Y-tracking helper with auto-page-break
            const ensureSpace = (needed) => {
                if (doc.y + needed > 760) {
                    doc.addPage();
                    if (isHighClassification) this._addWatermark(doc);
                    return true;
                }
                return false;
            };

            const isHighClassification = ['secret', 'top_secret'].includes(reportData.case_information?.classification?.toLowerCase());

            const drawSectionHeader = (title, number) => {
                ensureSpace(40);
                doc.moveDown(1.5);
                const currentY = doc.y;
                doc.fillColor(BRAND_COLOR).fontSize(12).font('Helvetica-Bold');
                doc.text(`${number}. ${title.toUpperCase()}`, 50, currentY, { characterSpacing: 0.5 });
                doc.moveTo(50, currentY + 14).lineTo(545, currentY + 14).lineWidth(1).stroke(BORDER_COLOR);
                doc.moveDown(1.2);
            };

            const printDate = new Date(reportData.report_metadata.generated_at).toISOString().replace('T', ' ').substring(0, 19) + ' UTC';
            
            // ─── Header ────────────────────────────────────────────────────
            if (isHighClassification) this._addWatermark(doc);
            doc.rect(0, 0, 600, 120).fill(BRAND_COLOR);
            
            // Logo / Title
            doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold')
                .text('TRACEVAULT', 50, 40);
            doc.fontSize(10).font('Helvetica')
                .text('SECURE FORENSIC PIPELINE', 50, 68, { characterSpacing: 1.5 });
            
            // Top Right Meta Info (Stack to avoid overlap)
            const metaX = 350;
            const metaW = 195;
            doc.fontSize(8).font('Helvetica-Bold').fillColor('#ffffff');
            doc.text(`REPORT ID: ${reportData.report_metadata.report_id.toUpperCase()}`, metaX, 35, { width: metaW, align: 'right' });
            doc.font('Helvetica').text(`GENERATED: ${printDate}`, metaX, doc.y + 2, { width: metaW, align: 'right' });
            doc.text(`EXAMINER: ${reportData.report_metadata.generated_by || 'SYSTEM'}`, metaX, doc.y + 2, { width: metaW, align: 'right' });
            doc.text(`CLASSIFICATION: ${(reportData.case_information?.classification || 'UNCLASSIFIED').toUpperCase()}`, metaX, doc.y + 2, { width: metaW, align: 'right' });

            doc.y = 140;

            // ─── 1. Case Information ───────────────────────────────────────
            drawSectionHeader('Case Information', '1');
            
            const caseInfo = reportData.case_information;
            if (caseInfo) {
                const startY = doc.y;
                doc.rect(50, startY, 495, 60).fill(LIGHT_BG);
                
                doc.fillColor(TEXT_COLOR).fontSize(9);
                doc.font('Helvetica-Bold').text('Case Reference:', 65, startY + 12);
                doc.font('Helvetica').text(caseInfo.case_name || 'N/A', 160, startY + 12);
                
                doc.font('Helvetica-Bold').text('Case Status:', 65, startY + 28);
                doc.font('Helvetica').text((caseInfo.status || 'ACTIVE').toUpperCase(), 160, startY + 28);

                doc.font('Helvetica-Bold').text('Opening Date:', 330, startY + 12);
                doc.font('Helvetica').text(new Date(caseInfo.created_at).toLocaleDateString(), 420, startY + 12);

                doc.font('Helvetica-Bold').text('Case ID:', 330, startY + 28);
                doc.font('Helvetica').fontSize(8).text(caseInfo.case_id, 420, startY + 28);
                
                doc.y = startY + 70;
            }

            // ─── 2. Evidence Technical Metadata ────────────────────────────
            drawSectionHeader('Evidence Technical Identity', '2');
            
            const em = reportData.evidence_metadata;
            const metaFields = [
                { label: 'File Name', value: em.file_name },
                { label: 'Evidence ID', value: em.evidence_id },
                { label: 'MIME Type', value: em.mime_type },
                { label: 'Binary Size', value: em.file_size_readable },
                { label: 'Upload Date', value: new Date(em.created_at).toUTCString() },
            ];

            metaFields.forEach(f => {
                doc.fillColor(MUTED_TEXT).font('Helvetica-Bold').fontSize(8).text(f.label.toUpperCase(), 50, doc.y, { continued: true });
                doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(9).text(`  ${f.value}`, 140, doc.y);
                doc.moveDown(0.4);
            });

            doc.moveDown(0.5);
            doc.fillColor(MUTED_TEXT).font('Helvetica-Bold').fontSize(8).text('SHA-256 PRIMARY HASH');
            doc.moveDown(0.3);
            doc.rect(50, doc.y, 495, 22).fill('#f1f5f9');
            doc.fillColor('#0f172a').font('Courier-Bold').fontSize(10).text(em.file_hash_sha256, 60, doc.y + 6);
            doc.moveDown(1.5);

            // ─── 3. Professional Description ──────────────────────────────
            if (em.description) {
                drawSectionHeader('Official Evidence Description', '3');
                doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(10).text(em.description, { align: 'justify', lineGap: 2 });
                doc.moveDown(1);
            }

            // ─── 4. Cryptographic Result Summary ───────────────────────────
            drawSectionHeader('Integrity Status & Verification', '4');
            
            const vr = reportData.verification_results;
            const isPass = vr.overall_result === 'pass';
            
            const resultY = doc.y;
            doc.rect(50, resultY, 495, 36).fill(isPass ? '#f0fdf4' : '#fef2f2').stroke(isPass ? '#bbf7d0' : '#fecaca');
            doc.fillColor(isPass ? ALERT_GREEN : ALERT_RED).fontSize(11).font('Helvetica-Bold')
                .text(isPass ? 'INTEGRITY VERIFIED: BIT-PERFECT MATCH' : 'WARNING: TAMPERING OR MODIFICATION DETECTED', 50, resultY + 12, { align: 'center', width: 495 });
            
            doc.moveDown(2.5);
            doc.fillColor(TEXT_COLOR).fontSize(9);
            doc.font('Helvetica-Bold').text('Methods Utilized:', { continued: true }).font('Helvetica').text(`  ${(vr.methods_run || []).join(', ').toUpperCase() || 'SHA-256, MULTI-HASH'}`);
            doc.font('Helvetica-Bold').text('Analysis Timestamp:', { continued: true }).font('Helvetica').text(`  ${new Date(vr.verification_timestamp).toUTCString()}`);
            
            // ─── 4.1 Advanced Forensic Deep Logic (FIXED OVERLAP) ──────────
            if (reportData.forensic_analysis) {
                doc.moveDown(1.5);
                doc.fillColor(BRAND_COLOR).fontSize(10).font('Helvetica-Bold').text('ADVANCED FORENSIC ANALYSIS (DEEP LOGIC)');
                doc.moveDown(0.8);
                
                const fa = reportData.forensic_analysis;
                const entropyRisk = fa.entropy?.risk === 'critical' || fa.entropy?.risk === 'high';
                const currentForensicY = doc.y;

                // Entropy Card
                doc.rect(50, currentForensicY, 240, 65).fill('#f8fafc').stroke(BORDER_COLOR);
                doc.fillColor(TEXT_COLOR).fontSize(8).font('Helvetica-Bold').text('SHANNON ENTROPY SCORE', 60, currentForensicY + 10);
                doc.fontSize(14).text(fa.entropy?.score.toFixed(4) || '0.0000', 60, currentForensicY + 24);
                doc.fontSize(8).fillColor(entropyRisk ? ALERT_RED : ALERT_GREEN)
                    .text(`${fa.entropy?.label || 'NORMAL'} - ${(fa.entropy?.risk || 'low').toUpperCase()} RISK`, 60, currentForensicY + 44);
                
                // Signature Card
                const sigX = 305;
                doc.rect(sigX, currentForensicY, 240, 65).fill('#f8fafc').stroke(BORDER_COLOR);
                doc.fillColor(TEXT_COLOR).fontSize(8).font('Helvetica-Bold').text('MAGIC BYTE VALIDATION', sigX + 10, currentForensicY + 10);
                doc.fontSize(9).text(`Expected: ${fa.signature?.expected?.toUpperCase() || 'UNKNOWN'}`, sigX + 10, currentForensicY + 24);
                doc.text(`Actual:   ${fa.signature?.actual?.toUpperCase() || 'UNKNOWN'}`, sigX + 10, currentForensicY + 38);
                
                const sigValid = fa.signature?.valid;
                doc.fontSize(7).font('Helvetica-Bold').fillColor(sigValid ? ALERT_GREEN : ALERT_RED)
                    .text(sigValid ? 'SIGNATURE INTEGRITY VERIFIED' : 'EXTENSION MISMATCH DETECTED', sigX + 10, currentForensicY + 50);
                
                doc.y = currentForensicY + 80;
            }

            // ─── 5. Chain of Custody Table ───────────────────────────────
            drawSectionHeader('Chain of Custody (Cryptographic Audit)', '5');
            
            // Header
            const headerY = doc.y;
            doc.rect(50, headerY, 495, 20).fill(BRAND_COLOR);
            doc.fillColor('#ffffff').fontSize(8).font('Helvetica-Bold');
            doc.text('DATE (UTC)', 55, headerY + 6);
            doc.text('ACTION / LABEL', 160, headerY + 6);
            doc.text('ACTOR / ENTITY', 280, headerY + 6);
            doc.text('IP ADDRESS', 380, headerY + 6);
            doc.text('EVENT HASH (S)', 470, headerY + 6);
            doc.y = headerY + 20;

            // Rows
            reportData.chain_of_custody.forEach((event, i) => {
                const rowHeight = 24;
                ensureSpace(rowHeight);
                
                const cy = doc.y;
                doc.rect(50, cy, 495, rowHeight).fill(i % 2 === 0 ? LIGHT_BG : '#ffffff');
                
                doc.fillColor(TEXT_COLOR).fontSize(7).font('Helvetica');
                doc.text(new Date(event.timestamp).toISOString().split('T')[0], 55, cy + 8);
                doc.font('Helvetica-Bold').text(event.action.substring(0, 24), 160, cy + 8);
                doc.font('Helvetica').text(event.actor.substring(0, 18), 280, cy + 8);
                doc.text(event.ip_address || '0.0.0.0', 380, cy + 8);
                
                const h = event.event_hash ? event.event_hash.substring(0, 8) : 'N/A';
                doc.font('Courier').text(h, 470, cy + 8);
                
                doc.y = cy + rowHeight;
            });
            
            doc.moveDown(2);

            // ─── 6. Digital Attestation ────────────────────────────────────
            drawSectionHeader('Legal Attestation', '6');
            doc.fontSize(8).fillColor(MUTED_TEXT).font('Helvetica')
                .text(reportData.legal_notice.statement, { align: 'justify', lineGap: 2 });
            
            doc.moveDown(2);
            doc.fillColor(TEXT_COLOR).fontSize(10).font('Helvetica-Bold').text('TECHNICAL ADVISORY');
            doc.fontSize(8).font('Helvetica').text(`Standards Compliance: ${reportData.legal_notice.standards.join(', ')}`);
            doc.text(`Platform Engine: ${reportData.legal_notice.platform}`);

            // Footer injection
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.moveTo(50, 790).lineTo(545, 790).stroke('#e2e8f0');
                doc.fillColor('#94a3b8').fontSize(7).font('Helvetica')
                    .text(`Electronic report generated by TraceVault. Verification remains active until ${new Date(Date.now() + 86400000).toLocaleDateString()}.`, 50, 800);
                doc.text(`Page ${i + 1} of ${pages.count}`, 500, 800);
            }

            doc.end();
        });
    }

    _generateCasePDF(reportData) {
        return new Promise((resolve, reject) => {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
            const chunks = [];
            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            const BRAND_COLOR = '#0369a1'; // Sky 700
            const TEXT_COLOR = '#0f172a';
            const LIGHT_BG = '#f8fafc';
            const BORDER_COLOR = '#e2e8f0';

            const classification = (reportData.case_information?.classification || 'unclassified').toLowerCase();
            const isHigh = ['secret', 'top_secret'].includes(classification);

            const ensureSpace = (needed) => { 
                if (doc.y + needed > 760) { 
                    doc.addPage(); 
                    if (isHigh) this._addWatermark(doc);
                    return true; 
                } 
                return false; 
            };

            const drawSectionHeader = (title, number) => {
                ensureSpace(40);
                doc.moveDown(1.5);
                const currentY = doc.y;
                doc.fillColor(BRAND_COLOR).fontSize(12).font('Helvetica-Bold');
                doc.text(`${number}. ${title.toUpperCase()}`, 50, currentY, { characterSpacing: 0.5 });
                doc.moveTo(50, currentY + 14).lineTo(545, currentY + 14).lineWidth(1).stroke(BORDER_COLOR);
                doc.moveDown(1.2);
            };

            if (isHigh) this._addWatermark(doc);

            // Header
            doc.rect(0, 0, 600, 120).fill(BRAND_COLOR);
            doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text('TRACEVAULT', 50, 40);
            doc.fontSize(10).font('Helvetica').text('FORENSIC CASE SUMMARY', 50, 68, { characterSpacing: 1.5 });
            doc.fontSize(8).font('Helvetica-Bold').text(`REPORT ID: ${reportData.report_metadata.report_id.toUpperCase()}`, 350, 35, { width: 195, align: 'right' });
            doc.font('Helvetica').text(`GENERATED: ${new Date(reportData.report_metadata.generated_at).toISOString().substring(0,19)} UTC`, 350, 45, { width: 195, align: 'right' });

            doc.y = 140;

            drawSectionHeader('Case Master View', '1');
            const ci = reportData.case_information;
            doc.rect(50, doc.y, 495, 80).fill(LIGHT_BG);
            doc.fillColor(TEXT_COLOR).fontSize(9);
            doc.font('Helvetica-Bold').text('Case Title:', 65, doc.y + 12);     doc.font('Helvetica').text(ci.case_name, 160, doc.y + 12);
            doc.font('Helvetica-Bold').text('Status:', 65, doc.y + 28);         doc.font('Helvetica').text((ci.status).toUpperCase(), 160, doc.y + 28);
            doc.font('Helvetica-Bold').text('Class:', 65, doc.y + 44);          doc.font('Helvetica').text((ci.classification).toUpperCase(), 160, doc.y + 44);
            doc.font('Helvetica-Bold').text('Case ID:', 330, doc.y + 12);       doc.font('Helvetica').text(ci.case_id, 420, doc.y + 12);
            doc.font('Helvetica-Bold').text('Opened:', 330, doc.y + 28);        doc.font('Helvetica').text(new Date(ci.created_at).toLocaleDateString(), 420, doc.y + 28);

            doc.y += 95;

            if (ci.description) {
                drawSectionHeader('Case Briefings', '2');
                doc.fillColor(TEXT_COLOR).font('Helvetica').fontSize(10).text(ci.description, { align: 'justify' });
            }

            drawSectionHeader('Investigation Team', '3');
            const team = reportData.investigators || [];
            if (team.length > 0) {
                doc.fillColor(TEXT_COLOR).fontSize(9).font('Helvetica').text(`Authorized Personnel: ${team.join(', ')}`);
            } else {
                doc.fillColor('#6b7280').fontSize(9).font('Helvetica').text('No external investigators assigned.');
            }
            doc.moveDown();

            drawSectionHeader('Linked Evidence Index', '4');
            reportData.linked_evidence.forEach((ev, i) => {
                ensureSpace(45);
                doc.rect(50, doc.y, 495, 42).fill(i % 2 === 0 ? LIGHT_BG : '#ffffff');
                doc.fillColor(TEXT_COLOR).fontSize(8).font('Helvetica-Bold').text(ev.file_name, 55, doc.y + 8);
                doc.font('Helvetica').text(`Size: ${ev.file_size_readable} | ID: ${ev.evidence_id.substring(0,18)}...`, 55, doc.y + 20);
                
                const integrityColor = ev.integrity === 'verified' ? '#059669' : '#b91c1c';
                doc.fillColor(integrityColor).font('Helvetica-Bold').text(ev.integrity.toUpperCase(), 320, doc.y + 8);
                doc.fillColor(TEXT_COLOR).font('Courier').fontSize(7).text(ev.hash, 320, doc.y + 22);
                doc.y += 42;
            });

            if (reportData.notes && reportData.notes.length > 0) {
                drawSectionHeader('Collaborative Briefing Notes', '5');
                reportData.notes.forEach((n, i) => {
                    ensureSpace(40);
                    doc.fillColor(BRAND_COLOR).fontSize(8).font('Helvetica-Bold').text(`${n.author.toUpperCase()} - ${new Date(n.timestamp).toLocaleDateString()}`);
                    doc.fillColor(TEXT_COLOR).fontSize(9).font('Helvetica').text(n.content, { indent: 10 });
                    doc.moveDown(0.5);
                });
            }

            // Footer
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.moveTo(50, 790).lineTo(545, 790).stroke('#e2e8f0');
                doc.fillColor('#64748b').fontSize(7).text(`TraceVault Forensic Case Summary | Security Class: ${classification.toUpperCase()}`, 50, 800);
                doc.text(`Page ${i + 1} of ${pages.count}`, 500, 800);
            }

            doc.end();
        });
    }

    _generateAuditPDF(reportData) {
        return new Promise((resolve, reject) => {
            const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true, layout: 'landscape' });
            const chunks = [];
            doc.on('data', (chunk) => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            const BRAND_COLOR = '#0f172a'; // Slate 900
            const TEXT_COLOR = '#1e293b';
            const LIGHT_BG = '#f1f5f9';
            
            const ensureSpace = (needed) => { if (doc.y + needed > 500) { doc.addPage(); return true; } return false; };

            // Header (Landscape)
            doc.rect(0, 0, 842, 90).fill(BRAND_COLOR);
            doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text('TRACEVAULT', 50, 30);
            doc.fontSize(10).font('Helvetica').text('MASTER SYSTEM AUDIT TRAIL // IMMUTABLE LEDGER', 50, 55, { characterSpacing: 1.5 });
            doc.fontSize(8).font('Helvetica-Bold').text(`TOTAL RECORDS EXPORTED: ${reportData.report_metadata.total_events_exported}`, 500, 30, { width: 290, align: 'right' });
            doc.font('Helvetica').text(`GENERATED: ${new Date(reportData.report_metadata.generated_at).toISOString().substring(0,19)} UTC`, 500, 45, { width: 290, align: 'right' });

            doc.y = 110;

            const headerY = doc.y;
            doc.rect(50, headerY, 742, 22).fill('#334155');
            doc.fillColor('#ffffff').fontSize(7).font('Helvetica-Bold');
            doc.text('DATE (UTC)', 55, headerY + 7);
            doc.text('ACTOR IDENTITY', 160, headerY + 7);
            doc.text('FORENSIC ACTION', 280, headerY + 7);
            doc.text('ENDPOINT REFERENCE', 400, headerY + 7);
            doc.text('SOURCE IP', 560, headerY + 7);
            doc.text('MAC / DEVICE FINGERPRINT', 650, headerY + 7);
            doc.y = headerY + 22;

            reportData.audit_events.forEach((ev, i) => {
                const rowHeight = 22;
                ensureSpace(rowHeight);
                const cy = doc.y;
                doc.rect(50, cy, 742, rowHeight).fill(i % 2 === 0 ? LIGHT_BG : '#ffffff');
                doc.fillColor(TEXT_COLOR).fontSize(6).font('Helvetica');
                doc.text(new Date(ev.timestamp).toISOString().replace('T', ' ').substring(0, 19), 55, cy + 8);
                doc.text((ev.user || '').substring(0, 18), 160, cy + 8);
                doc.font('Helvetica-Bold').text(ev.action.substring(0, 24), 280, cy + 8);
                doc.font('Helvetica').text((ev.endpoint || '').substring(0, 40), 400, cy + 8);
                doc.text(ev.ip_address || '0.0.0.0', 560, cy + 8);
                doc.font('Courier').text(`${ev.mac_address || '—'} / ${(ev.device_fingerprint || 'unknown').substring(0, 12)}`, 650, cy + 8);
                doc.y = cy + rowHeight;
            });

            // Footer
            const pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.fillColor('#94a3b8').fontSize(6).text(`TraceVault System Audit Ledger | Generated by ${reportData.report_metadata.generated_by}`, 50, 560);
                doc.text(`Page ${i + 1} of ${pages.count}`, 780, 560);
            }

            doc.end();
        });
    }

    _addWatermark(doc) {
        doc.save();
        doc.fillColor('#fecaca').opacity(0.15);
        doc.fontSize(60).font('Helvetica-Bold');
        doc.rotate(-45, { origin: [300, 400] });
        doc.text('CONFIDENTIAL // TOP SECRET', 50, 400, { align: 'center', width: 500 });
        doc.restore();
    }
}

function formatBytes(bytes) {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

export const reportService = new ReportService();
